(defun joma-csv-align () 
  "Aligns columns of a buffer visting a csv file. The SEPARATOR parameter
specifies the column separator. The default value is a comma `,'"
  (interactive)
  (save-excursion
    (setq line-elements-lengths (list))
    (beginning-of-buffer)
    (while (not (eobp))
      (let ((element-position 0))
	(setq line-elements-lengths-temp (list))
	(beginning-of-line)
	(setq line-elements (split-string  
			     (buffer-substring (line-beginning-position) (line-end-position)) 
			     "|"))
	(dolist (element line-elements) 
      	  (cond ((eq nil (nth 0 line-elements-lengths))
      		 (push (length element) line-elements-lengths-temp))
      		((>  (length element) (nth 0 line-elements-lengths))
      		 (push (length element) line-elements-lengths-temp))
      		((<=  (length element) (nth 0 line-elements-lengths))
      		 (push (nth 0 line-elements-lengths) line-elements-lengths-temp)))
	  (pop line-elements-lengths)
	  (setq element-position (1+ element-position)))
	(if (> (length line-elements-lengths) 0)
	    (setq line-elements-lengths (nconc (nreverse line-elements-lengths-temp) line-elements-lengths))
	  (setq line-elements-lengths (nreverse line-elements-lengths-temp))
	  )
	(princ line-elements-lengths)
	(forward-line)))))